"""create table trackings

Revision ID: 52a915bf78b7
Revises: 904c423dac2a
Create Date: 2024-03-25 23:25:13.532380
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52a915bf78b7'
down_revision: Union[str, None] = '904c423dac2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    commands auto generated by Alembic - please adjust! ###
    """
    op.create_table(
        'trackings',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
            comment='Identificador único do rastreamento',
        ),
        sa.Column(
            'code',
            sa.String(length=13),
            nullable=False,
            comment='Código único de rastreio dos correios',
        ),
        sa.Column(
            'data',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='Dados do rastreamento da encomenda',
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Última data de atualização dos dados',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Data de criação dos dados',
        ),
        sa.PrimaryKeyConstraint('id'),
        comment='Armazena todos os rastreamentos do sistema',
    )
    op.create_index(
        op.f('ix_trackings_code'), 'trackings', ['code'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    commands auto generated by Alembic - please adjust! ###
    """
    op.drop_index(op.f('ix_trackings_code'), table_name='trackings')
    op.drop_table('trackings')
    # ### end Alembic commands ###
