"""create table user

Revision ID: 904c423dac2a
Revises:
Create Date: 2024-03-25 23:19:10.622638
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '904c423dac2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    commands auto generated by Alembic - please adjust!
    """
    op.create_table(
        'user',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
            comment='Identificador único do usuário',
        ),
        sa.Column(
            'telegram_id',
            sa.BigInteger(),
            nullable=False,
            comment='ID do Telegram do usuário',
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Última data de atualização dos dados',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Data de criação dos dados',
        ),
        sa.PrimaryKeyConstraint('id'),
        comment='Armazena todos os usuários do sistema',
    )
    op.create_index(
        op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    commands auto generated by Alembic - please adjust!
    """
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
